<#
Event Log Archive and Cleanup Utility (Safe Mode)
Author: DWP Engineer Support Script
PowerShell: 5.1

This script archives Windows Event Logs and performs cleanup only when it is safe.
It is designed to avoid destructive behavior by never deleting records unless a full log clear is possible.
#>

[CmdletBinding(DefaultParameterSetName = 'Cleanup')]
param(
    # This parameter defines the list of event logs to process.
    [Parameter(ParameterSetName = 'Cleanup')]
    [string[]]$LogName = @('Application', 'System', 'Security'),

    # This parameter controls how old records must be to qualify for cleanup decisions.
    [Parameter(ParameterSetName = 'Cleanup')]
    [ValidateRange(0, 3650)]
    [int]$OlderThanDays = 3,

    # This switch performs a non-destructive preview and prints the count of records that would be deleted.
    [Parameter(ParameterSetName = 'Cleanup')]
    [switch]$DryRun,

    # This parameter sets the root folder where archives and manifests are written.
    [Parameter(ParameterSetName = 'Cleanup')]
    [Parameter(ParameterSetName = 'Rollback')]
    [string]$ArchiveRoot,

    # This parameter sets the folder where timestamped run logs are written.
    [Parameter(ParameterSetName = 'Cleanup')]
    [Parameter(ParameterSetName = 'Rollback')]
    [string]$LogDirectory,

    # This switch runs rollback mode using a prior manifest.
    [Parameter(ParameterSetName = 'Rollback', Mandatory = $true)]
    [switch]$Rollback,

    # This parameter points to a specific manifest generated by a cleanup run.
    [Parameter(ParameterSetName = 'Rollback')]
    [string]$ManifestPath
)

# This section enables strict mode to catch undeclared variables and similar script issues early.
Set-StrictMode -Version Latest

# This section resolves default folders relative to the script location.
$scriptRoot = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($scriptRoot)) {
    $scriptRoot = Split-Path -Path $MyInvocation.MyCommand.Path -Parent
}

if ([string]::IsNullOrWhiteSpace($ArchiveRoot)) {
    $ArchiveRoot = Join-Path -Path $scriptRoot -ChildPath 'eventlog-archive'
}

if ([string]::IsNullOrWhiteSpace($LogDirectory)) {
    $LogDirectory = Join-Path -Path $scriptRoot -ChildPath 'logs'
}

# This section prepares timestamp values used in archive names, manifest names, and log file names.
$runTime = Get-Date
$runStamp = $runTime.ToString('yyyyMMdd-HHmmss')
$dateTag = $runTime.ToString('yyyyMMdd')

function Ensure-Directory {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    # This section creates directories only when needed, which keeps repeated runs idempotent.
    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -Path $Path -ItemType Directory -Force | Out-Null
    }
}

# This section creates working directories used by the script.
Ensure-Directory -Path $ArchiveRoot
Ensure-Directory -Path $LogDirectory

$manifestDirectory = Join-Path -Path $ArchiveRoot -ChildPath 'manifests'
$restoredDirectory = Join-Path -Path $ArchiveRoot -ChildPath 'rollback-restored'
Ensure-Directory -Path $manifestDirectory
Ensure-Directory -Path $restoredDirectory

# This section creates a run-specific, timestamped log file.
$runLogPath = Join-Path -Path $LogDirectory -ChildPath ("eventlog-archive-cleanup-{0}.log" -f $runStamp)

function Write-Log {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,

        [ValidateSet('INFO', 'WARN', 'ERROR')]
        [string]$Level = 'INFO'
    )

    # This section writes each log line to both console and the run log file.
    $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $line = "[{0}] [{1}] {2}" -f $stamp, $Level, $Message
    Add-Content -Path $runLogPath -Value $line
    Write-Host $line
}

function Get-SafeLogFileName {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    # This section converts event log names into file-safe names for archive files.
    return ($Name -replace '[^a-zA-Z0-9_.-]', '_')
}

function Get-LatestManifestPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ManifestFolder
    )

    # This section resolves the newest manifest for rollback mode when one is not explicitly supplied.
    try {
        $latest = Get-ChildItem -Path $ManifestFolder -Filter '*.json' -File -ErrorAction Stop |
            Sort-Object -Property LastWriteTime -Descending |
            Select-Object -First 1

        if ($null -eq $latest) {
            return $null
        }

        return $latest.FullName
    } catch {
        Write-Log -Level 'ERROR' -Message ("Failed to locate latest manifest. {0}" -f $_.Exception.Message)
        return $null
    }
}

function Get-OldRecordCount {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name,

        [Parameter(Mandatory = $true)]
        [datetime]$Cutoff
    )

    # This section counts records older than the configured cutoff.
    try {
        $count = (Get-WinEvent -FilterHashtable @{ LogName = $Name; EndTime = $Cutoff } -ErrorAction Stop |
            Measure-Object).Count
        return [int64]$count
    } catch {
        Write-Log -Level 'ERROR' -Message ("Failed counting old records for log '{0}'. {1}" -f $Name, $_.Exception.Message)
        return -1
    }
}

function Export-LogArchive {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name,

        [Parameter(Mandatory = $true)]
        [string]$Destination
    )

    # This section exports the full log to EVTX so the script can support rollback and safe recovery.
    try {
        $null = & wevtutil epl "$Name" "$Destination" 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "wevtutil epl exited with code $LASTEXITCODE"
        }
        return $true
    } catch {
        Write-Log -Level 'ERROR' -Message ("Failed exporting log '{0}' to '{1}'. {2}" -f $Name, $Destination, $_.Exception.Message)
        return $false
    }
}

function Clear-EventLogSafe {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    # This section clears a log only after archive succeeds and only when cleanup criteria allow a full clear.
    try {
        $null = & wevtutil cl "$Name" 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "wevtutil cl exited with code $LASTEXITCODE"
        }
        return $true
    } catch {
        Write-Log -Level 'ERROR' -Message ("Failed clearing log '{0}'. {1}" -f $Name, $_.Exception.Message)
        return $false
    }
}

function Invoke-CleanupMode {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Names,

        [Parameter(Mandatory = $true)]
        [int]$AgeDays,

        [Parameter(Mandatory = $true)]
        [bool]$IsDryRun
    )

    # This section computes the cutoff timestamp and initializes counters for the run summary.
    $cutoff = (Get-Date).AddDays(-$AgeDays)
    $summary = [ordered]@{
        Mode = if ($IsDryRun) { 'DryRun' } else { 'Cleanup' }
        OlderThanDays = $AgeDays
        Cutoff = $cutoff
        LogsProcessed = 0
        ArchivesCreated = 0
        ArchivesSkippedIdempotent = 0
        LogsCleared = 0
        RecordsToDeleteDryRun = 0
        RecordsDeleted = 0
        PartialOldRecordsSkipped = 0
        Errors = 0
    }

    $manifest = New-Object System.Collections.Generic.List[object]
    Write-Log -Message ("Cleanup mode started. OlderThanDays={0}; Cutoff={1}" -f $AgeDays, $cutoff)

    # This section processes each requested event log independently so one failure does not stop the run.
    foreach ($name in $Names) {
        $summary.LogsProcessed++
        Write-Log -Message ("Processing log: {0}" -f $name)

        $recordCount = 0
        $newestTime = $null
        $oldRecordCount = -1

        try {
            $logInfo = Get-WinEvent -ListLog $name -ErrorAction Stop
            $recordCount = if ($null -eq $logInfo.RecordCount) { 0 } else { [int64]$logInfo.RecordCount }
        } catch {
            $summary.Errors++
            Write-Log -Level 'ERROR' -Message ("Failed reading log metadata for '{0}'. {1}" -f $name, $_.Exception.Message)
            continue
        }

        if ($recordCount -eq 0) {
            Write-Log -Message ("Log '{0}' has no records. Nothing to archive or clean." -f $name)
            continue
        }

        try {
            $newest = Get-WinEvent -LogName $name -MaxEvents 1 -ErrorAction Stop
            $newestTime = $newest.TimeCreated
        } catch {
            $summary.Errors++
            Write-Log -Level 'ERROR' -Message ("Failed reading newest event for '{0}'. {1}" -f $name, $_.Exception.Message)
            continue
        }

        $oldRecordCount = Get-OldRecordCount -Name $name -Cutoff $cutoff
        if ($oldRecordCount -lt 0) {
            $summary.Errors++
            continue
        }

        $canClearWholeLog = $newestTime -lt $cutoff
        $safeName = Get-SafeLogFileName -Name $name
        $archiveFolder = Join-Path -Path $ArchiveRoot -ChildPath $safeName
        $archivePathToday = Join-Path -Path $archiveFolder -ChildPath ("{0}-{1}.evtx" -f $safeName, $dateTag)

        try {
            Ensure-Directory -Path $archiveFolder
        } catch {
            $summary.Errors++
            Write-Log -Level 'ERROR' -Message ("Failed ensuring archive folder '{0}'. {1}" -f $archiveFolder, $_.Exception.Message)
            continue
        }

        # This section enforces idempotency by skipping archive and cleanup when today's archive already exists.
        if (Test-Path -LiteralPath $archivePathToday) {
            $summary.ArchivesSkippedIdempotent++
            Write-Log -Level 'WARN' -Message ("Skipping '{0}' because today's archive already exists: {1}" -f $name, $archivePathToday)
            continue
        }

        if ($IsDryRun) {
            $toDelete = if ($canClearWholeLog) { $recordCount } else { 0 }
            $summary.RecordsToDeleteDryRun += $toDelete
            if (-not $canClearWholeLog -and $oldRecordCount -gt 0) {
                $summary.PartialOldRecordsSkipped += $oldRecordCount
            }

            Write-Host ("DryRun: Log='{0}' TotalRecords={1} OldRecords={2} WouldDelete={3}" -f $name, $recordCount, $oldRecordCount, $toDelete)
            Write-Log -Message ("DryRun result for '{0}': TotalRecords={1}; OldRecords={2}; WouldDelete={3}; CanClearWholeLog={4}" -f $name, $recordCount, $oldRecordCount, $toDelete, $canClearWholeLog)
            continue
        }

        $archived = Export-LogArchive -Name $name -Destination $archivePathToday
        if (-not $archived) {
            $summary.Errors++
            continue
        }

        $summary.ArchivesCreated++
        Write-Log -Message ("Archive created for '{0}': {1}" -f $name, $archivePathToday)

        if ($canClearWholeLog) {
            $cleared = Clear-EventLogSafe -Name $name
            if ($cleared) {
                $summary.LogsCleared++
                $summary.RecordsDeleted += $recordCount
                Write-Log -Message ("Cleared log '{0}'. DeletedRecords={1}" -f $name, $recordCount)
            } else {
                $summary.Errors++
            }
        } else {
            if ($oldRecordCount -gt 0) {
                $summary.PartialOldRecordsSkipped += $oldRecordCount
            }
            Write-Log -Level 'WARN' -Message ("Skipped clear for '{0}' because newer records exist. OldRecords={1}" -f $name, $oldRecordCount)
        }

        $manifest.Add([pscustomobject]@{
            LogName = $name
            ArchivePath = $archivePathToday
            ArchiveDate = $dateTag
            Cutoff = $cutoff.ToString('o')
            TotalRecordsAtRun = $recordCount
            OldRecordsAtRun = $oldRecordCount
            Cleared = $canClearWholeLog
            Timestamp = $runTime.ToString('o')
        }) | Out-Null
    }

    # This section writes a manifest that rollback mode can use to recover archived data copies.
    $manifestPath = $null
    if (-not $IsDryRun -and $manifest.Count -gt 0) {
        $manifestPath = Join-Path -Path $manifestDirectory -ChildPath ("eventlog-manifest-{0}.json" -f $runStamp)
        try {
            $manifest | ConvertTo-Json -Depth 5 | Set-Content -Path $manifestPath -Encoding UTF8
            Write-Log -Message ("Manifest created: {0}" -f $manifestPath)
        } catch {
            $summary.Errors++
            Write-Log -Level 'ERROR' -Message ("Failed writing manifest '{0}'. {1}" -f $manifestPath, $_.Exception.Message)
            $manifestPath = $null
        }
    }

    return [pscustomobject]@{
        Summary = $summary
        ManifestPath = $manifestPath
        LogFile = $runLogPath
    }
}

function Invoke-RollbackMode {
    param(
        [string]$InputManifestPath
    )

    # This section resolves the rollback manifest and initializes rollback summary counters.
    $effectiveManifest = $InputManifestPath
    if ([string]::IsNullOrWhiteSpace($effectiveManifest)) {
        $effectiveManifest = Get-LatestManifestPath -ManifestFolder $manifestDirectory
    }

    if ([string]::IsNullOrWhiteSpace($effectiveManifest) -or -not (Test-Path -LiteralPath $effectiveManifest)) {
        throw 'Rollback failed: no valid manifest was found.'
    }

    $summary = [ordered]@{
        Mode = 'Rollback'
        ManifestPath = $effectiveManifest
        EntriesRead = 0
        ArchiveCopiesRestored = 0
        MissingArchives = 0
        Errors = 0
    }

    Write-Log -Message ("Rollback mode started. Manifest={0}" -f $effectiveManifest)

    # This section rehydrates archived EVTX files into a rollback-restored folder for safe recovery and review.
    # Note: Windows Event Logs cannot be safely re-injected into active channels via a native selective import API.
    try {
        $entries = Get-Content -Path $effectiveManifest -Raw -ErrorAction Stop | ConvertFrom-Json -ErrorAction Stop
    } catch {
        throw ("Rollback failed while reading manifest. {0}" -f $_.Exception.Message)
    }

    $entryList = @($entries)
    $summary.EntriesRead = $entryList.Count

    foreach ($entry in $entryList) {
        try {
            if (-not (Test-Path -LiteralPath $entry.ArchivePath)) {
                $summary.MissingArchives++
                Write-Log -Level 'WARN' -Message ("Rollback source archive missing: {0}" -f $entry.ArchivePath)
                continue
            }

            $safeName = Get-SafeLogFileName -Name $entry.LogName
            $restorePath = Join-Path -Path $restoredDirectory -ChildPath ("{0}-{1}-restored.evtx" -f $safeName, $dateTag)

            if (Test-Path -LiteralPath $restorePath) {
                Write-Log -Level 'WARN' -Message ("Rollback skipped existing restored file (idempotent): {0}" -f $restorePath)
                continue
            }

            Copy-Item -LiteralPath $entry.ArchivePath -Destination $restorePath -Force -ErrorAction Stop
            $summary.ArchiveCopiesRestored++
            Write-Log -Message ("Rollback restored archive copy: {0}" -f $restorePath)
        } catch {
            $summary.Errors++
            Write-Log -Level 'ERROR' -Message ("Rollback operation failed for '{0}'. {1}" -f $entry.LogName, $_.Exception.Message)
        }
    }

    return [pscustomobject]@{
        Summary = $summary
        ManifestPath = $effectiveManifest
        LogFile = $runLogPath
    }
}

try {
    # This section routes script execution to cleanup mode or rollback mode.
    if ($PSCmdlet.ParameterSetName -eq 'Rollback') {
        $result = Invoke-RollbackMode -InputManifestPath $ManifestPath
    } else {
        $result = Invoke-CleanupMode -Names $LogName -AgeDays $OlderThanDays -IsDryRun $DryRun.IsPresent
    }

    # This section prints a concise run summary for operators.
    Write-Host ''
    Write-Host '========== Event Log Archive/Cleanup Summary ==========' -ForegroundColor Cyan
    foreach ($k in $result.Summary.Keys) {
        Write-Host ("{0}: {1}" -f $k, $result.Summary[$k])
    }
    Write-Host ("LogFile: {0}" -f $result.LogFile)
    if ($result.ManifestPath) {
        Write-Host ("ManifestPath: {0}" -f $result.ManifestPath)
    }
    Write-Host '=======================================================' -ForegroundColor Cyan
} catch {
    # This section handles unexpected top-level errors and keeps a record in the run log.
    Write-Log -Level 'ERROR' -Message $_.Exception.Message
    throw
}
